version: '3.9'

services:
  web:
    container_name: web
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 5000:5000
    expose:
      - 5000
    environment:
      - ASPNETCORE_URLS=http://0.0.0.0:
    tty: true
    labels:
        - traefik.enable=true
        - traefik.http.routers.chat.entrypoints=http-point
        - traefik.http.routers.chat.rule=PathPrefix(`/chat/`)
        - traefik.http.middlewares.chat-replacepathregex.replacepathregex.regex=^/chat/(.*)
        - traefik.http.middlewares.chat-replacepathregex.replacepathregex.replacement=/$$1
        - traefik.http.routers.chat.middlewares=chat-replacepathregex
  proxy:
    container_name: proxy
    build:
        context: ./Proxy
    ports:
        - 80:80
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - ./Proxy/traefik.yml:/traefik.yml:ro
