version: '3.3'

services:
  web:
    container_name: web
    build:
      context: .
      dockerfile: ./Dockerfile.test
    ports:
      - 5000:5000
    environment:
      - ASPNETCORE_URLS=http://0.0.0.0:5000
