log:
  level: INFO

api:
  insecure: false
  dashboard: false

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: true

entryPoints:
  http-point:
    address: :80
  https-point:
    address: :443
